### ISSUE TITLE
Choosing some basic fonts for the website

### ISSUE THREAD

**Issue by erupturatis** [NavigoLearn/Navigo-FrontEnd#29]

**Comment by sopyb** [comment]
1.  https://fonts.google.com/specimen/Roboto (Android default Font - [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) - Requires license and copyright notices to be present in copies of the software distributed)
Roboto is a neo-grotesque sans-serif typeface family developed by Google as the system font for its mobile operating system Android ([Source](https://en.wikipedia.org/wiki/Roboto))

2.  https://fonts.google.com/specimen/Kanit ([Open Font Licence](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) - Same as above)
It is a combination of concepts, mixing a Humanist Sans Serif motif with the curves of Capsulated Geometric styles that makes it suitable for various uses, contemporary and futuristic ([Source](https://fonts.google.com/specimen/Kanit))

3.  https://fonts.google.com/specimen/Oxygen ([Open Font Licence](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) - Same as above)
Oxygen is a sans-serif typeface family created as part of the KDE Project, a libre desktop for the GNU+Linux operating system ([Source](https://fonts.google.com/specimen/Oxygen))
